// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	entity "project-auction/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// PGCommentRepository is an autogenerated mock type for the PGCommentRepository type
type PGCommentRepository struct {
	mock.Mock
}

// InsertComment provides a mock function with given fields: _a0
func (_m *PGCommentRepository) InsertComment(_a0 entity.Comment) (entity.Comment, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for InsertComment")
	}

	var r0 entity.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.Comment) (entity.Comment, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(entity.Comment) entity.Comment); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(entity.Comment)
	}

	if rf, ok := ret.Get(1).(func(entity.Comment) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPGCommentRepository creates a new instance of PGCommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPGCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PGCommentRepository {
	mock := &PGCommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
